import type {
  Amenity,
  Booking,
  CreditLedgerEntry,
  ScenarioKey,
  ScenarioTurn,
  User,
} from "./types";

export const currentUser: User = {
  id: "u1",
  name: "Chirag",
  org: "Google",
  building: "Tower A",
  role: "employee",
  avatarInitial: "C",
  monthlyAllowance: 40,
  eligibility: "All amenities",
  voiceEnabled: true,
};

export const STARTING_CREDITS = 24;

export const amenities: Amenity[] = [
  {
    id: "am-emerald",
    name: "Emerald Meeting Room",
    type: "Meeting room",
    building: "Tower A",
    floor: "8",
    capacity: 6,
    costCredits: 0,
    active: true,
    workingHours: "08:00 – 20:00",
    availableDays: "Monday–Friday",
    minDurationMins: 30,
    maxDurationMins: 120,
    defaultDurationMins: 60,
    allowedDurationsLabel: "30m, 1h, 1h30m, 2h",
    advanceBookingDaysLabel: "14 days",
    maxActiveBookingsPerUser: 3,
    bookingFrequency: "2 per day",
    eligibilityRule: "All employees",
    cancellationPolicy: "Free until 30 min before",
    description: "6-seat meeting room with display and whiteboard",
    guidelines:
      "Maximum booking duration: 2 hours\nMaximum attendees: 8\nExternal guests: Not allowed\nFood: Not allowed\nAvailable Monday–Friday\nOperating hours: 8 AM–8 PM",
    shotLabel: "room photo",
    availabilityLabel: "FREE UNTIL 3 PM",
    lastEditedAt: "4 days ago",
    lastEditedBy: "Priya N.",
  },
  {
    id: "am-sapphire",
    name: "Sapphire Meeting Room",
    type: "Meeting room",
    building: "Tower A",
    floor: "8",
    capacity: 10,
    costCredits: 0,
    active: true,
    workingHours: "08:00 – 20:00",
    availableDays: "Monday–Friday",
    minDurationMins: 30,
    maxDurationMins: 180,
    defaultDurationMins: 60,
    allowedDurationsLabel: "30m, 1h, 1h30m, 2h, 3h",
    advanceBookingDaysLabel: "14 days",
    maxActiveBookingsPerUser: 3,
    bookingFrequency: "2 per day",
    eligibilityRule: "All employees",
    cancellationPolicy: "Free until 30 min before",
    description: "10-seat meeting room with video conferencing",
    guidelines:
      "Maximum booking duration: 3 hours\nMaximum attendees: 12\nExternal guests: Allowed with notice\nFood: Allowed\nAvailable Monday–Friday\nOperating hours: 8 AM–8 PM",
    shotLabel: "room photo",
    availabilityLabel: "AVAILABLE NOW",
    lastEditedAt: "4 days ago",
    lastEditedBy: "Priya N.",
  },
  {
    id: "am-ruby",
    name: "Ruby Meeting Room",
    type: "Meeting room",
    building: "Tower A",
    floor: "6",
    capacity: 4,
    costCredits: 0,
    active: true,
    workingHours: "08:00 – 20:00",
    availableDays: "Monday–Friday",
    minDurationMins: 30,
    maxDurationMins: 60,
    defaultDurationMins: 60,
    allowedDurationsLabel: "30m, 1h",
    advanceBookingDaysLabel: "7 days",
    maxActiveBookingsPerUser: 3,
    bookingFrequency: "2 per day",
    eligibilityRule: "All employees",
    cancellationPolicy: "Free until 30 min before",
    description: "4-seat huddle room",
    guidelines:
      "Maximum booking duration: 1 hour\nMaximum attendees: 4\nExternal guests: Not allowed\nFood: Not allowed\nAvailable Monday–Friday\nOperating hours: 8 AM–8 PM",
    shotLabel: "room photo",
    availabilityLabel: "AVAILABLE NOW",
    lastEditedAt: "4 days ago",
    lastEditedBy: "Priya N.",
  },
  {
    id: "am-diamond",
    name: "Diamond Conference Room",
    type: "Conference room",
    building: "Tower A",
    floor: "12",
    capacity: 15,
    costCredits: 10,
    active: true,
    workingHours: "08:00 – 20:00",
    availableDays: "Monday–Friday",
    minDurationMins: 60,
    maxDurationMins: 240,
    defaultDurationMins: 60,
    allowedDurationsLabel: "1h, 2h, 3h, 4h",
    advanceBookingDaysLabel: "30 days",
    maxActiveBookingsPerUser: 3,
    bookingFrequency: "1 per day",
    eligibilityRule: "Managers and above",
    cancellationPolicy: "Free until 2 h before",
    description: "15-seat conference room with AV desk",
    guidelines:
      "Maximum booking duration: 4 hours\nMaximum attendees: 15\nExternal guests: Allowed with notice\nFood: Allowed\nAvailable Monday–Friday\nOperating hours: 8 AM–8 PM\nApproval required for bookings over 2 hours",
    shotLabel: "room photo",
    availabilityLabel: "BUSY UNTIL 4 PM",
    lastEditedAt: "4 days ago",
    lastEditedBy: "Priya N.",
  },
  {
    id: "am-gym",
    name: "Gym",
    type: "Fitness",
    building: "Tower A",
    floor: "2",
    capacity: 10,
    costCredits: 10,
    active: true,
    workingHours: "06:00 – 21:00",
    availableDays: "All days",
    minDurationMins: 60,
    maxDurationMins: 60,
    defaultDurationMins: 60,
    allowedDurationsLabel: "1h",
    advanceBookingDaysLabel: "7 days",
    maxActiveBookingsPerUser: 1,
    bookingFrequency: "1 per day",
    eligibilityRule: "All employees",
    cancellationPolicy: "Free until 2 h before",
    description: "Cardio and strength floor with showers",
    guidelines:
      "Maximum booking duration: 1 hour\nMaximum attendees: 1\nExternal guests: Not allowed\nFood: Not allowed\nAvailable all days\nOperating hours: 6 AM–9 PM",
    shotLabel: "gym photo",
    availabilityLabel: "4 SLOTS TODAY",
    lastEditedAt: "4 days ago",
    lastEditedBy: "Priya N.",
  },
  {
    id: "am-theater",
    name: "Theater",
    type: "Theater",
    building: "Tower A",
    floor: "1",
    capacity: 30,
    costCredits: 20,
    active: true,
    workingHours: "10:00 – 22:00",
    availableDays: "All days",
    minDurationMins: 60,
    maxDurationMins: 180,
    defaultDurationMins: 120,
    allowedDurationsLabel: "1h, 2h, 3h",
    advanceBookingDaysLabel: "30 days",
    maxActiveBookingsPerUser: 1,
    bookingFrequency: "1 per day",
    eligibilityRule: "Named list",
    cancellationPolicy: "Non-refundable",
    description: "30-seat screening theater",
    guidelines:
      "Maximum booking duration: 3 hours\nMaximum attendees: 30\nExternal guests: Allowed with notice\nFood: Allowed\nAvailable all days\nOperating hours: 10 AM–10 PM\nApproval required",
    shotLabel: "theater photo",
    availabilityLabel: "2 SLOTS TODAY",
    lastEditedAt: "4 days ago",
    lastEditedBy: "Priya N.",
  },
  {
    id: "am-tabletennis",
    name: "Table Tennis",
    type: "Recreation",
    building: "Tower A",
    floor: "2",
    capacity: 4,
    costCredits: 2,
    active: false,
    workingHours: "08:00 – 20:00",
    availableDays: "All days",
    minDurationMins: 30,
    maxDurationMins: 30,
    defaultDurationMins: 30,
    allowedDurationsLabel: "30m",
    advanceBookingDaysLabel: "7 days",
    maxActiveBookingsPerUser: 2,
    bookingFrequency: "2 per day",
    eligibilityRule: "All employees",
    cancellationPolicy: "Free until 30 min before",
    description: "Two table tennis boards in the lounge",
    guidelines:
      "Maximum booking duration: 30 minutes\nMaximum attendees: 4\nExternal guests: Not allowed\nFood: Not allowed\nAvailable all days\nOperating hours: 8 AM–8 PM",
    shotLabel: "lounge photo",
    availabilityLabel: "AVAILABLE NOW",
    lastEditedAt: "4 days ago",
    lastEditedBy: "Priya N.",
  },
];

export function findAmenity(id: string): Amenity | undefined {
  return amenities.find((a) => a.id === id);
}

export const initialUpcomingBookings: Booking[] = [
  {
    id: "b1",
    displayId: "AMN-20481",
    amenityId: "am-emerald",
    amenityName: "Emerald Meeting Room",
    place: "Tower A · Floor 8",
    when: "Today · 3:00–4:00 PM",
    meta: "5 attendees",
    attendees: 5,
    costCredits: 0,
    status: "confirmed",
    createdVia: "voice",
  },
  {
    id: "b2",
    displayId: "AMN-20455",
    amenityId: "am-gym",
    amenityName: "Gym",
    place: "Tower A · Floor 2",
    when: "Tomorrow · 6:00–7:00 PM",
    meta: "10 credits",
    attendees: 1,
    costCredits: 10,
    status: "confirmed",
    createdVia: "text",
  },
  {
    id: "b3",
    displayId: "AMN-20460",
    amenityId: "am-diamond",
    amenityName: "Conference Room Diamond",
    place: "Tower A · Floor 12",
    when: "Friday · 11:00 AM–12:00 PM",
    meta: "10 credits",
    attendees: 6,
    costCredits: 10,
    status: "confirmed",
    createdVia: "manual",
  },
];

export const pastBookings: Booking[] = [
  {
    id: "b4",
    displayId: "AMN-20390",
    amenityId: "am-tabletennis",
    amenityName: "Table Tennis",
    place: "Floor 2",
    when: "Yesterday · 5:30–6:00 PM",
    meta: "2 credits",
    attendees: 2,
    costCredits: 2,
    status: "completed",
    createdVia: "text",
  },
  {
    id: "b5",
    displayId: "AMN-20321",
    amenityId: "am-theater",
    amenityName: "Theater",
    place: "Floor 1",
    when: "Sep 2 · 7:00–9:00 PM",
    meta: "20 credits",
    attendees: 12,
    costCredits: 20,
    status: "cancelled",
    createdVia: "manual",
  },
];

export const initialLedger: CreditLedgerEntry[] = [
  { id: "l1", name: "Gym · Tomorrow 6:00 PM", date: "SEP 9, 2026", amount: -10 },
  { id: "l2", name: "Conference Room Diamond · Friday", date: "SEP 7, 2026", amount: -10 },
  { id: "l3", name: "Monthly allowance", date: "SEP 1, 2026", amount: 40 },
  { id: "l4", name: "Table Tennis · Sep 8", date: "AUG 31, 2026", amount: -2 },
];

const scenarioBase: Record<ScenarioKey, Omit<ScenarioTurn, "trace">> = {
  unavailable: {
    user: "Book Emerald at 3 PM for one hour.",
    agent: "Emerald is unavailable at 3 PM.",
    optionsTitle: "VALID ALTERNATIVES · TODAY",
    options: [
      { name: "Emerald", detail: "4:00–5:00 PM", tag: "AVAILABLE" },
      { name: "Emerald", detail: "2:00–3:00 PM", tag: "AVAILABLE" },
      { name: "Sapphire", detail: "3:00–4:00 PM", tag: "AVAILABLE" },
    ],
    actions: [],
    resultTitle: "Booking confirmed.",
    resultBody: null,
    blockTitle: null,
    blockBody: null,
  },
  paid: {
    user: "Book the gym at 6 PM.",
    agent: "",
    optionsTitle: "",
    options: [],
    actions: [],
    resultTitle: "Booking confirmed.",
    resultBody: null,
    blockTitle: null,
    blockBody: null,
  },
  low: {
    user: "Book the gym at 6 PM.",
    agent: "The gym costs 10 credits, but you only have 4 credits remaining.",
    optionsTitle: "",
    options: [],
    actions: [{ label: "Contact admin", kind: "primary" }],
    resultTitle: "Request sent to workplace admin.",
    resultBody:
      "Priya N. will review your credit top-up request. You will be notified in AmenityOS.",
    blockTitle: "Your booking cannot be completed.",
    blockBody:
      "Insufficient credits. Paid amenities require the full credit cost at time of booking.",
  },
  capacity: {
    user: "Book the Ruby meeting room for 8 people.",
    agent:
      "Ruby Meeting Room has a capacity of 4.\nI can check larger rooms at the same time.",
    optionsTitle: "ROOMS THAT FIT 8 · 3:00–4:00 PM",
    options: [
      { name: "Emerald", detail: "Floor 8 · capacity 6", tag: "TOO SMALL BY 2" },
      { name: "Sapphire", detail: "Floor 8 · capacity 10", tag: "FITS 8" },
    ],
    actions: [],
    resultTitle: "Booking confirmed.",
    resultBody: null,
    blockTitle: null,
    blockBody: null,
  },
};

export const scenarioLabels: { key: ScenarioKey; label: string }[] = [
  { key: "unavailable", label: "Slot unavailable" },
  { key: "paid", label: "Paid amenity" },
  { key: "low", label: "Insufficient credits" },
  { key: "capacity", label: "Capacity exceeded" },
];

export const scenarioTraces: Record<ScenarioKey, string> = {
  unavailable: "availability checked · 3 conflicting holds · 0 credits required",
  paid: "eligibility passed · credit hold placed · confirmation required by policy",
  low: "credit check failed · 4 of 10 required · booking not created",
  capacity: "capacity rule enforced · attendees 8 · 2 candidate rooms",
};

export function getScenarioBase(key: ScenarioKey) {
  return scenarioBase[key];
}
